# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chris Uyehara
author: Christopher M. Uyehara
email: cuyehara@email.unc.edu
avatar: /assets/images/headshot.jpg
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Christopher M. Uyehara <br>
  Graduate student | Biomedical scientist |
  Lover of obscure facts | Champion of the mighty <i>Drosophila dragonagaster</i> |
  Writer of grandiloquent pronouncements <br><br>
  <i>Carpe Diem. Carpe Annum. Carpe Everything.</i>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cmuyehara.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cmuyehara
github_username:  cmuyehara
markdown: kramdown
#
# Build settings
#theme: minima
#theme: jekyll-theme-hamilton
theme: not-pure-poole
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:title

# Google Analytics
google_analytics: G-ZZPB07QBPR

skin: daylight

# theme settings:
cover_bg_color: rgb(2,21,69)


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
